

STIPE_COUNTRIES = [
    {"name": "Australia (AU)", "code": "AU"},
    {"name": "Austria (AT)", "code": "AT"},
    {"name": "Belgium (BE)", "code": "BE"},
    {"name": "Brazil (BR)", "code": "BR"},
    {"name": "Bulgaria (BG)", "code": "BG"},
    {"name": "Canada (CA)", "code": "CA"},
    {"name": "Cyprus (CY)", "code": "CY"},
    {"name": "Czech Republic (CZ)", "code": "CZ"},
    {"name": "Denmark (DK)", "code": "DK"},
    {"name": "Estonia (EE)", "code": "EE"},
    {"name": "Finland (FI)", "code": "FI"},
    {"name": "France (FR)", "code": "FR"},
    {"name": "Germany (DE)", "code": "DE"},
    {"name": "Gibraltar (GI)", "code": "GI"},
    {"name": "Greece (GR)", "code": "GR"},
    {"name": "Hong Kong (HK)", "code": "HK"},
    {"name": "Hungary (HU)", "code": "HU"},
    {"name": "India (IN)", "code": "IN"},
    {"name": "Ireland (IE)", "code": "IE"},
    {"name": "Italy (IT)", "code": "IT"},
    {"name": "Japan (JP)", "code": "JP"},
    {"name": "Liechtenstein (LI)", "code": "LI"},
    {"name": "Lithuania (LT)", "code": "LT"},
    {"name": "Luxembourg (LU)", "code": "LU"},
    {"name": "Latvia (LV)", "code": "LV"},
    {"name": "Malta (MT)", "code": "MT"},
    {"name": "Malaysia (MY)", "code": "MY"},
    {"name": "Mexico (MX)", "code": "MX"},
    {"name": "Netherlands (NL)", "code": "NL"},
    {"name": "New Zealand (NZ)", "code": "NZ"},
    {"name": "Norway (NO)", "code": "NO"},
    {"name": "Poland (PL)", "code": "PL"},
    {"name": "Portugal (PT)", "code": "PT"},
    {"name": "Romania (RO)", "code": "RO"},
    {"name": "Singapore (SG)", "code": "SG"},
    {"name": "Slovakia (SK)", "code": "SK"},
    {"name": "Slovenia (SI)", "code": "SI"},
    {"name": "Spain (ES)", "code": "ES"},
    {"name": "Sweden (SE)", "code": "SE"},
    {"name": "Switzerland (CH)", "code": "CH"},
    {"name": "United Kingdom (GB)", "code": "GB"},
    {"name": "United States (US)", "code": "US"}
]
